### ISSUE TITLE
Installation fails /opt/ftldb*: No such file or directory

### ISSUE THREAD

**Issue by pepwork** [PhilippSalvisberg/docker-oddgendemo-cdb#1]
Hi Philipp

The installation of the docker container ocdb is running fine 
until this statement in /assets/entrypoint.sh:

`. /assets/install_ftldb.sh`

Error in log of ocdb
`/assets/install_ftldb.sh: line 3: cd: /opt/ftldb*: No such file or directory`

Docker container setup stops and no further component is installed.
My workaround to overcome this issue:

- Download the missing ftldb installation files from [Github ftldb repository](https://github.com/ftldb/ftldb/releases)
- Copy the file into the docker container
- Unzip/Extract the tar file
- Copy extracted folder to /opt
- Change owner to oracle
- Create a second install file with the missing installation steps
- Copy the file into the docker container
- Run the file

Enjoy 

Docker commands used:
`docker start ocdb`
`docker cp ftldb-ora-1.5.0-install-linux.tar.gz ocdb:/opt`
`docker exec ocdb chown oracle:dba /opt/ftldb-ora-1.5.0-install-linux.tar.gz`
`docker exec ocdb gunzip /opt/ftldb-ora-1.5.0-install-linux.tar.gz`
`docker exec ocdb tar -xf /opt/ftldb-ora-1.5.0-install-linux.tar`
`docker exec ocdb mv /ftldb-ora-1.5.0 /opt`
`docker exec ocdb chown -R oracle:dba /opt/ftldb-ora-1.5.0`

entrypoint2.sh
`#!/bin/bash`
`# set environment `
`. /assets/setenv.sh`
`# Exit script on non-zero command exit status`
`set -e`
`echo "Installing FTLDB."`
`. /assets/install_ftldb.sh`
`echo "Installing tePLSQL."`
`. /assets/install_teplsql.sh`
`echo "Installing oddgen examples/tutorials"`
`. /assets/install_oddgen.sh`

`docker cp entrypoint2.sh ocdb:/assets`
`docker exec ocdb /assets/entrypoint2.sh`

**Comment by PhilippSalvisberg** [comment]
Hello Perry,

Thank you for the detailed issue report. The image was build at a time when just a release candidate for FTLDB v1.5.0 was available. In the meantime v1.5.0 has been made availabe available and the release  candidate has been deleted. Creating a container based on an existing image (v1.0.0) worked fine, but building the image using the dockerfile failed. Issue has been fixed and v1.0.1 of the image uses the latest FTLDB version.

Cheers,
Philipp
