### ISSUE TITLE
DBCA Operation failed.

### ISSUE THREAD

**Issue by nmrao** [PhilippSalvisberg/docker-oddgendemo-cdb#3]
First of thank you for the image @ https://hub.docker.com/r/phsalvisberg/oddgendemo-cdb/

Getting below issue:

[ 2017-03-16 08:26:43.882 UTC ] Copying database files
DBCA_PROGRESS : 1%
DBCA_PROGRESS : 13%
DBCA_PROGRESS : 25%
[ 2017-03-16 08:31:57.232 UTC ] Creating and starting Oracle instance
DBCA_PROGRESS : 26%
DBCA_PROGRESS : 30%
DBCA_PROGRESS : 31%
DBCA_PROGRESS : 35%
DBCA_PROGRESS : 38%
[ 2017-03-16 08:43:57.631 UTC ] Error while executing "/u01/app/oracle/product/12.2.0.1/dbhome/rdbms/admin/dbmssml.sql". Refer to "/u01/app/oracle/cfgtoollogs/dbca/ocdb/dbmssml0.log" for more details. Error in Process: /u01/app/oracle/product/12.2.0.1/dbhome/perl/bin/perl
[ 2017-03-16 08:45:02.611 UTC ] DBCA_PROGRESS : DBCA Operation failed.

And there isn't anything in `/u01/app/oracle/cfgtoollogs/dbca/ocdb/dbmssml0.log` file.
Tried couple of times and stuck in the same location. Any pointers?

**Comment by PhilippSalvisberg** [comment]
I'd try the following:

- check if there is enough memory for the container available (```docker system info | grep 'Memory'```and ```docker stats```). 2GB is really the minimum required for the container.
- start the container interactively. e.g.  ```docker run -it -p 1522:1522 -p 8083-8084:8083-8084 -h ocdb --name ocdb phsalvisberg/oddgendemo-cdb``` - This way it is easier to evaluate the state of the crashed installation. Restarting dbca is also an option (see line 28ff in https://github.com/PhilippSalvisberg/docker-oddgendemo-cdb/blob/master/assets/entrypoint.sh)

Good luck.

**Comment by nmrao** [comment]
Thank you for the swift response. Will check it.

**Comment by nmrao** [comment]
Looks, it is going out-of-memory.
Tried even using `--memory="3g"`, but it is still taking 2GB only when checked thru `docker stats` command.

**Comment by PhilippSalvisberg** [comment]
I was not able to reproduce this behaviour on my Mac.

However, I finally managed to reproduce it under Windows 10 using Docker for Windows 17.03.0-ce, when

* the virtual disk image ```MobyLinuxVM.vhdx``` was on a drive with enabled compression
* using a locally mapped volume, e.g. ```-v e:\docker\ocdb\u01\app\oracle:/u01/app/oracle```

After moving the virtual disk image ```MobyLinuxVM.vhdx``` to an uncompressed drive, the database was created successfully.  You can move the virtual disk image within the "Advanced" section. Just choose a new location and the file will be moved (you do not loose downloaded images or containers).

**Comment by PhilippSalvisberg** [comment]
I've done some additional tests. 

Locally mapped volumes are not stable in Docker for Windows 17.03.0-ce. In fact when I try to create the image using 

```
docker run -it -v e:\docker\ocdb\u01\app\oracle:/u01/app/oracle -p 1522:1522 -p 8083-8084:8083-8084 -h ocdb --name ocdb phsalvisberg/oddgendemo-cdb
```

the container crashes while executing ```dbmssml.sql``` (it does not matter where ```MobyLinuxVM.vhdx``` is located). This indicates a Docker problem. The container must not crash when an operation within a container fails.

The following works repeatably:

```
docker run -d -p 1522:1522 -p 8083-8084:8083-8084 -h ocdb --name ocdb phsalvisberg/oddgendemo-cdb
``` 

A workaround might be to create a locally mapped volume after a successful installation. See also [Backup](https://github.com/PhilippSalvisberg/docker-oddgendemo-cdb#backup) and [Restore](https://github.com/PhilippSalvisberg/docker-oddgendemo-cdb#restore). But I guess you will run into other problems sooner or later.
