### ISSUE TITLE
ORDS on Tomcat with Java

### ISSUE THREAD

**Issue by yachtsman60** [PhilippSalvisberg/docker-oddgendemo-cdb#4]
Hi Philipp,
Thank you for creating such a compact and useful docker image of Oracle 12c and Apex 5.1.
I was wondering if you could easily add Tomcat with the ORDS web listener configured to the installed database, recognising that this will also require Java JRE to be added.
I have tried to merge your dockerfile with the dockerfiles found here https://github.com/lucassampsouza/ords_apex/tree/master/3.0.1-apex501 or more likely here https://github.com/araczkowski/docker-oracle-apex-ords but unfortunately I am struggling to get everything to play nicely!
Regards
Ollie

**Comment by PhilippSalvisberg** [comment]
Hello Ollie,

Thanks for the enhancement request. Of course it is possible to add Tomcat and ORDS to the image. But I do not want to make the current image bigger. Beside that I could imagine a lot of database unrelated requests such as to use another Tomcat version or application server (WebLogic or Glassfish, ...) or even a standalone ORDS installation. Therefore I really think a separate, dedicated container should be used for ORDS when using Docker.

However, I've amended the image v2.0.2 to get ready for ORDS, means that the users ```APEX_LISTENER```, ```APEX_REST_PUBLIC_USER``` and ```APEX_PUBLIC_USERS``` are provided with the same password as SYS/SYSTEM. You may "upgrade" your current v2.0.1 container by running the following command (while the container ```ocdb``` is running):

```
docker exec -t ocdb /bin/bash -c "cd /u01/app/oracle/product/12.2.0.1/dbhome/apex && echo -e 'oracle\noracle' | /opt/sqlcl/bin/sql -s -l sys/oracle@localhost:1522/opdb1.docker AS sysdba @apex_rest_config.sql && echo -e 'ALTER USER APEX_PUBLIC_USER ACCOUNT UNLOCK;\n ALTER USER APEX_PUBLIC_USER IDENTIFIED BY oracle;\nEXIT\n' | /opt/sqlcl/bin/sql -s -l sys/oracle@localhost:1522/opdb1.docker AS SYSDBA"
```

After creating the ```ocdb``` container with ```docker run -d -p 1522:1522 -p 8083-8084:8083-8084 -h ocdb --name ocdb phsalvisberg/oddgendemo-cdb``` (or after upgrading an existing container as explained above) you may create a separate ```ords``` Tomcat container which is using the ```ocdb``` container (see ```--link``` below):

```
docker run  -it --link ocdb:ocdb --name ords \
    -e DATABASE_HOSTNAME="ocdb" \
    -e DATABASE_PORT="1522" \
    -e DATABASE_SERVICENAME="opdb1.docker" \
    -e DATABASE_PUBLIC_USER_PASS="oracle" \
    -e APEX_LISTENER_PASS="oracle" \
    -e APEX_REST_PASS="oracle" \
    -e ORDS_PASS="oracle" \
    -p 9090:8080 lucassampsouza/ords_apex:3.0.9-apex51
``` 

The first time you are running this container you are prompted for the ```SYS``` user and password to enable ORDS to create and initialise missing schemas.

I think this is quite a simple solution (without using docker-compose). I hope you agree.

Regards
Philipp
