### ISSUE TITLE
Issue wit the latest

### ISSUE THREAD

**Issue by dentaku65** [PhilippSalvisberg/docker-oddgendemo-cdb#8]
The docker run command exit with this message:
 /assets/install_apex.sh: /u01/app/oracle/product/12.2.0.1/dbhome/sqldeveloper/sqlcl/bin/sql: /bin/bash: bad interpreter: Text file busy

**Comment by PhilippSalvisberg** [comment]
How have you started the container (all command line arguments)? What's the OS and docker version? Thank you.

**Comment by dentaku65** [comment]
Hi,

Docker version:  1.13.1
OS: Ubuntu 16.04.2 LTS

Container executed as:
docker run -d -p 0.0.0.0:1522:1522 -p 0.0.0.0:8083-8084:8083-8084 -h ocdb --name ocdb -e ORACLE_ALLOW_REMOTE=true phsalvisberg/oddgendemo-cdb

thx

**Comment by PhilippSalvisberg** [comment]
Hmm, cannot reproduce it under MacOS 10.12 and Win 10. I guess this is reproducible every time, right? 

Looks similar to the problem described in https://github.com/oracle/docker-images/issues/232 and and https://github.com/moby/moby/issues/9547 .

According to the description one should add a ```sync``` after the chmod +x... (after line 43 in /assets/install_apex.sh)

```
chmod +x ${ORACLE_HOME}/sqldeveloper/sqlcl/bin/sql
echo -e "\n\n${APEX_PASS}" | ${ORACLE_HOME}/sqldeveloper/sqlcl/bin/sql -s -l sys/${PASS}@${PDB_NAME} AS sysdba @apxchpwd.sql
```

I'll try to reproduce it in a Ubuntu VM, but this will take some time.

**Comment by PhilippSalvisberg** [comment]
As a workaround you may run 
```
docker run -d -p 0.0.0.0:1522:1522 -p 0.0.0.0:8083-8084:8083-8084 -h ocdb --name ocdb -e ORACLE_ALLOW_REMOTE=true -e WEB_CONSOLE=false phsalvisberg/oddgendemo-cdb
```
and install APEX and configure XDB afterwards.

**Comment by dentaku65** [comment]
@PhilippSalvisberg 
At the moment I'm using an old image and I'm stay with that one; I can wait for the update one

**Comment by PhilippSalvisberg** [comment]
Image v2.1.1 tested under Ubuntu. Works.
